### ISSUE TITLE
Write selenium tests related to admin functionalities on this website

### ISSUE THREAD

**Issue by ldanielw1** [ldanielw1/mSpray#14]

**Comment by austinzhang323** [comment]
Hi Taipei, is this the same as #12? I'm assuming the only things that deal with users have to do with admin functions in deleting/editing data, and the site admin tab

**Comment by ldanielw1** [comment]
Unfortunately, it's different, because admins can not only edit/delete users, they can also edit/delete spray workers, spray data, etc.
