### ISSUE TITLE
Write selenium tests that not only test that add_data modals open up, etc., but also success of the marker addition, etc.

### ISSUE THREAD

**Issue by ldanielw1** [ldanielw1/mSpray#21]
Should do this for all kinds of data

**Comment by austinzhang323** [comment]
Hi Taipei, should I work on this next or #12? Actually, for both not sure how to start -- for this success thing, the website doesn't actually let you add a flag, so not sure what it'll look like when it does haha; and for the users functions, is that that the three tabs on the left hand side?

**Comment by ldanielw1** [comment]
either is fine - and user functions would require that you make yourself an admin...

run this in your terminal (in the project directory):
```
rake toggle_admin_settings YOUR_EMAIL on
```
