### ISSUE TITLE
OAuth client deleted

### ISSUE THREAD

**Issue by austinzhang323** [ldanielw1/mSpray#26]
![Screen Shot 2022-03-31 at 2.41.00 PM.png](https://images.zenhubusercontent.com/623bf1db4f7a854dd92bda8b/67aa536b-5532-457b-ab31-29be6c21f6e0)

**Comment by ldanielw1** [comment]
We need to re-create credential secrets for this project in a secure way (where we don't check the secrets into the repo). The way we're going to do this is:
1. You need to log in to https://console.cloud.google.com
2. Create a new project
3. Click on the menu in the top left -> "APIs & Services" -> "Enabled APIs & Services"
4. Enable: Google Drive API, Google Sheets API, Maps Javascript API, Maps Embed API
5. Click on the menu in the top left -> "APIs & Services" -> "Credentials"
6. Create an API key, and type the following into your terminal: `echo 'export GOOGLE_MAPS_APIKEY="THENEWAPIKEY"' >> ~/.bashrc` (replace `THENEWAPIKEY` with the api key code).
7. Create a new OAuth key (for web applications), and with the following for the "Authorized redirect URIs": `http://127.0.0.1:3000/google_sign_in/callback`, `https://127.0.0.1:3000/google_sign_in/callback`, `http://localhost:3000/google_sign_in/callback`, `https://localhost:3000/google_sign_in/callback`
8. Type the following into your terminal: `echo 'export MSPRAY_OAUTH_CLIENT_ID="CLIENTID"' >> ~/.bashrc` (replace `CLIENTID` with the client id for the oauth key)
9. Type the following into your terminal: `echo 'export MSPRAY_OAUTH_CLIENT_SECRET="CLIENTSECRET"' >> ~/.bashrc` (replace `CLIENTSECRET` with the new oauth key's client secret)

**Comment by austinzhang323** [comment]
Hi Taipei! it seems like the code in the repo has not been changed and still has the old client ids coded in. Should I just edit it myself to the ENV["GOOGLE_MAPS_APIKEY"], ENV["MSPRAY_OAUTH_CLIENT_ID"], and ENV["MSPRAY_OAUTH_CLIENT_SECRET"]?

**Comment by austinzhang323** [comment]
just kidding for the google maps api key one it's too hard to figure out lol, can you help please? :)

**Comment by austinzhang323** [comment]
jkjk got it to work :) I'll push it with my newest code in a bit
