### ISSUE TITLE
Write resume entry for mSpray

### ISSUE THREAD

**Issue by ldanielw1** [ldanielw1/mSpray#34]
Upload here, I'll take a look

**Comment by austinzhang323** [comment]
Malaria Spray — QA Automation Engineer
FEBRUARY 2022 – PRESENT | Boston, MA
Developed black box testing suite of the Malaria Spray web app using rails, selenium and rspec
Automated QA of all functions on app by interacting with CSS elements, and wrote 30+ test cases
Collaborated with other engineers and maintained code through github
