### ISSUE TITLE
Install the selenium-webdriver gem into the codebase

### ISSUE THREAD

**Issue by ldanielw1** [ldanielw1/mSpray#4]
https://github.com/simplecov-ruby/simplecov

**Comment by ldanielw1** [comment]
Hey Austin! haven't seen your PR yet for this change - can you please take a look at this wiki article on pushing changes to repository?

https://github.com/ldanielw1/mSpray/wiki/Working-Guidelines

**Comment by austinzhang323** [comment]
On it!

**Comment by austinzhang323** [comment]
Hi Taipei! got a question, I pushed the changes in the branch added_selenium... and when i run the command git pr, it says pr is not recognized; and when i try git pull, it says my branch is up to date. how do i make a new request?

**Comment by ldanielw1** [comment]
yep - it needs to be `gh pr create --fill` - that will auto-generate your PR for you

**Comment by austinzhang323** [comment]
Hi Taipei, `gh` `github` and `pr` are not recognized commands in the terminal. what should I do?

**Comment by ldanielw1** [comment]
you'll need to run `brew install gh`
